version: '3.5'
services:
    redis:
        image: redis
        container_name: redis-m2
        ports:
            - '6379:6379'
        volumes:
            - ${PWD}/data:/data
            - ${PWD}/csv:/csv
        networks:
            - redis-replication
        environment:
            - REDIS_DATABASES=16
            - REDIS_MAXMEMORY=256mb

    redis-2:
        image: redis
        container_name: redis-m2-replica-2
        ports:
            - '6380:6379'
        networks:
            - redis-replication
        depends_on:
            - redis
        environment:
            - REDIS_DATABASES=16
            - REDIS_MAXMEMORY=256mb
        command: redis-server --slaveof redis 6379
networks:
    redis-replication:
        driver: bridge
