version: '3.5'
services:
    client:
        build: ./client
        container_name: client
        # stdin_open: true
        ports:
            - '5173:5173'
            - '5174:5174'
        volumes:
            - ./client:/usr/src/client
            - /usr/src/client/node_modules
        links:
            - server
        restart: on-failure
        networks:
            - redis-project-network

    server:
        build: ./server
        container_name: server
        ports:
            - '3000:3000'
        volumes:
            - ./server:/usr/src/server
            - /usr/src/server/node_modules
        links:
            - redis
        environment:
            PORT: 3000
            REDIS_URL: redis://redis-m2:6379
            # POSTGRES_URI: postgres://mohamad:123321@db:5432/postgres
        restart: on-failure
        networks:
            - redis-project-network

    redis:
        image: redis/redis-stack
        container_name: redis-m2
        ports:
            - '6379:6379'
            - '8001:8001'
        # volumes:
        # - ${PWD}/data:/data
        # - ${PWD}/csv:/csv
        networks:
            - redis-project-network
        environment:
            - REDIS_DATABASES=16
            - REDIS_MAXMEMORY=256mb

    redis-2:
        image: redis/redis-stack
        container_name: redis-m2-replica-2
        ports:
            - '6380:6379'
        networks:
            - redis-project-network
        depends_on:
            - redis
        environment:
            - REDIS_DATABASES=16
            - REDIS_MAXMEMORY=256mb
        command: redis-server --slaveof redis 6379
networks:
    redis-project-network:
        driver: bridge
