version: "3.9"

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: mohamad
            POSTGRES_PASSWORD: 123321
            POSTGRES_DB: fastapi
        networks:
            - postgres
        expose:
            - 8000
            - 5432
        ports:
            - 5432:5432
        # deploy:
        #     restart_policy:
        #         condition: on-failure # condition: none, on-failure, or any (default)
        #         delay: 3s # Duration between restart attempts
        #         max_attempts: 3 # Maximum number of attempts outside of the restart window
        #         window: 120s # Duration for determining if a restart is successful

    fastapi:
        build: .
        container_name: fastapi_dynamic
        expose:
            - 5432
            - 8000
        ports:
            - 8000:8000
        networks:
            - postgres
        # volumes:
        #     - fastapi_volume:/fastapi
        volumes:
            - .:/fastapi
        deploy:
            restart_policy:
                condition: on-failure # condition: none, on-failure, or any (default)
                delay: 3s # Duration between restart attempts
                max_attempts: 3 # Maximum number of attempts outside of the restart window
                window: 120s # Duration for determining if a restart is successful

networks:
    postgres:
        driver: bridge
# volumes:
#     fastapi_volume:
