version: "3.9"

services:
    frontend:
        build: ./
        container_name: sky-scanner-frontend
        ports:
            - 3000:3000
        volumes:
            - ./:/app
            - /app/node_modules
        networks:
            - default
        deploy:
            restart_policy:
                condition: on-failure # condition: none, on-failure, or any (default)
                delay: 3s # Duration between restart attempts
                max_attempts: 3 # Maximum number of attempts outside of the restart window
                window: 120s # Duration for determining if a restart is successful