version: "3.9"

services:
    postgres:
        hostname: postgres.com
        image: postgres
        container_name: postgres_compose
        environment:
            POSTGRES_USER: mohamad
            POSTGRES_PASSWORD: 123321
            POSTGRES_DB: fastapi
        networks:
            - postgres

        expose:
            - 5432
            - 8000
            - 3000
        ports:
            - 5432:5432

    backend:
        # build: backend/
        container_name: backend_compose
        image: dockerregistryjedi.azurecr.io/backend_compose
        expose:
            - 5432
            - 8000
            - 3000
        ports:
            - 8000:8000
        networks:
            - postgres
        deploy:
            restart_policy:
                condition: on-failure # condition: none, on-failure, or any (default)
                delay: 3s # Duration between restart attempts
                max_attempts: 3 # Maximum number of attempts outside of the restart window
                window: 120s # Duration for determining if a restart is successful

    frontend:
        # build: frontend/
        image: dockerregistryjedi.azurecr.io/frontend_compose
        container_name: frontend_compose
        expose:
            - 5432
            - 8000
            - 3000
        ports:
            - 80:3000
        networks:
            - postgres
        deploy:
            restart_policy:
                condition: on-failure # condition: none, on-failure, or any (default)
                delay: 3s # Duration between restart attempts
                max_attempts: 3 # Maximum number of attempts outside of the restart window
                window: 120s # Duration for determining if a restart is successful


networks:
    postgres:
        driver: bridge
        # ipam:
        #     config:
        #         - subnet: 10.5.0.0/16
        #           gateway: 10.5.0.1
