version: "3.9"
services:
    app:
        build: .
        container_name: redis_app_container
        ports:
            - 8000:8000

    redis:
        image: redis
        ports:
            - 6379:6379
