name: Build and Push Docker Image

on: [push] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest

