version: '3.8'

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toto

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
